TARGET_SIM ?= ckb-vm

RUN_TARGET= $(TARGET_SIM) $< > $@

RISCV_PREFIX   ?= riscv64-unknown-elf-
RISCV_GCC      ?= $(RISCV_PREFIX)gcc
RISCV_OBJDUMP  ?= $(RISCV_PREFIX)objdump
RISCV_GCC_OPTS ?= -static -mcmodel=medany -fvisibility=hidden -nostdlib -nostartfiles -DXLEN=$(XLEN) $(RVTEST_DEFINES)

COMPILE_TARGET=\
	$$(RISCV_GCC) $(2) $$(RISCV_GCC_OPTS) \
		-I$(TARGETDIR)/$(RISCV_TARGET)/ \
		-I$(ROOTDIR)/../riscv-arch-test/riscv-test-suite/env/ \
		-T$(TARGETDIR)/$(RISCV_TARGET)/link.ld $$< \
		-o $$@; \
	$$(RISCV_OBJDUMP) -D $$@ > $$@.objdump
